### ISSUE TITLE
Bad hash function for smt2 terms.

### ISSUE THREAD

**Issue by BrunoDutertre** [murxla/murxla#6]
In file `smt2_solver.cpp` the hash function and the equality tests are not consistent.

It's possible for two terms to be equal (as defined by`Smt2Term::equals`) but hash to different values (i.e., have different ids). Especially, a newly created term has id 0 but could be equal to an existing term of id non-zero.

This causes assertion failures as in:
```
./bin/murxla --seed 4 --strings --no-uf
...
Assertion failed: (!res || a->get_id() == 0 || b->get_id() == 0 || a->get_id() == b->get_id()), function operator==, file solver.cpp, line 757.
Abort
```

**Comment by mpreiner** [comment]
Thanks Bruno! This one's a bit tricky since the smt2 printer doesn't do full hash consing for terms (like other solvers do) and probably requires some refactoring in the smt2 printer. We'll keep you posted!

**Comment by BrunoDutertre** [comment]
Thanks. I'll post an easier issue soon.

I use this fix in my local copy. It seems to work. Is this incorrect somehow?
```
static inline size_t mix(size_t state, size_t h) {
  const size_t a = 0xc6a4a7935bd1e995;

  h *= a;
  h ^= h >> 47;
  h *= a;
  state ^= h;
  return a * state;
}

size_t
Smt2Term::hash() const
{
  // assume 64bit size_t
  //
  // the hash function must not depend on d_id & d_leaf_kind
  // (as d_id & d_leak_kind may be set after the term is created and added
  // to an unordered_map), but the id of the children terms are already set
  // when the term is created.
  //
  size_t h = 0xabcdef0123456;

  h = mix(h, std::hash<std::string>{}(d_kind));
  h = mix(h, std::hash<size_t>{}(d_args.size()));
  h = mix(h, std::hash<size_t>{}(d_indices.size()));
  if (get_kind() == Op::UNDEFINED) {
    h = mix(h, std::hash<std::string>{}(d_repr));
  } else {
    size_t i = 0;
    size_t n = d_args.size();
    for (i = 0; i < n; i++) {
      h = mix(h, std::hash<uint64_t>{}(d_args[i]->get_id()));
    }
    n = d_str_args.size();
    for (i = 0; i < n; i++) {
      h = mix(h, std::hash<std::string>{}(d_str_args[i]));
    }
    n = d_indices.size();
    for (i = 0; i < n; i++) {
      h = mix(h, std::hash<uint32_t>{}(d_indices[i]));
    }
  }
  return h;
}
```

**Comment by mpreiner** [comment]
I just tested your fix on my machine and it still fails with the above error.

**Comment by mpreiner** [comment]
@BrunoDutertre Can you test if https://github.com/murxla/murxla/commit/4b5da5767092de97277d8c48a42864c6ca98f02a fixes this issue for you? It looks like the issue in your code was that equals() considered the leaf kind, but this was set at a later point. Including the leaf kind in the hash and setting the leaf kind before doing the hash table lookup seems to fix the issue now.

**Comment by BrunoDutertre** [comment]
It seems to work. Thanks.
